export declare function HasPrefixSlash(inputPath: string): boolean;
export declare function HasTrailingSlash(inputPath: string): boolean;
export declare function EnsureTrailingSlash(inputPath: string): string;
export declare function EnsureNoPrefixSlash(inputPath: string): string;
export declare function EnsurePrefixSlash(inputPath: string): string;
export declare function EnsureNoTrailingSlash(inputPath: string): string;
export declare function EnsureAbsolutePathFile(filePath: string): string;
export declare function EnsureAbsolutePathDir(folderPath: string): string;
export declare function EnsureGoogleStoragePathDir(folderPath: string): string;
export declare function EnsureGoogleStoragePathFile(filePath: string): string;
export declare function GetRelativePath(currentDirectoryPath: string, absObjectPath: string): string;
export declare function IsCurrentPath(currentDirectoryPath: string, absObjectPath: string): boolean;
export declare function IsCurrentPathFile(currentDirectoryPath: string, absObjectPath: string): boolean;
export declare function GetSubDirectory(currentDirectoryPath: string, absObjectPath: string): string;
